export const counter = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT'
};

export const todos = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  TOGGLE_ITEM_COMPLETED: 'TOGGLE_ITEM_COMPLETED',
  REMOVE_COMPLETED: 'REMOVE_COMPLETED'
}

